#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

if ! command -v stow >/dev/null 2>&1; then
  echo "stow is required. Install it with your package manager (e.g. 'brew install stow' or 'apt install stow')." >&2
  exit 1
fi

TARGET_DIR="${STOW_TARGET:-$HOME}"
DEFAULT_PACKAGES="ghostty lazygit nvim rofi starship sway tmux waybar yazi zsh"
PACKAGES="${PACKAGES:-$DEFAULT_PACKAGES}"
read -r -a package_list <<<"$PACKAGES"

show_help() {
  cat <<'EOF'
Usage: ./setup.sh [stow flags] [--unlink-symlinks|--no-unlink-symlinks] [--backup]

Options:
  --unlink-symlinks     Remove existing symlinks in ~/.config that would conflict.
  --no-unlink-symlinks  Disable the default unlinking of conflicting symlinks.
  --backup              Move conflicting targets into .backup/<timestamp>/.
  -h, --help            Show this help.

Environment:
  STOW_TARGET  Target directory (default: $HOME)
  PACKAGES     Space-separated package list to stow.
EOF
}

STOW_ARGS=()
UNLINK_SYMLINKS=true
BACKUP=false

for arg in "$@"; do
  case "$arg" in
    --unlink-symlinks|--unlink)
      UNLINK_SYMLINKS=true
      ;;
    --no-unlink-symlinks|--no-unlink)
      UNLINK_SYMLINKS=false
      ;;
    --backup)
      BACKUP=true
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      STOW_ARGS+=("$arg")
      ;;
  esac
done

prepare_targets() {
  local backup_root=""
  if $BACKUP; then
    backup_root="$ROOT/.backup/$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$backup_root/.config"
  fi

  for pkg in "${package_list[@]}"; do
    local cfg_dir="$ROOT/$pkg/.config"
    [ -d "$cfg_dir" ] || continue

    while IFS= read -r -d '' entry; do
      local name target
      name="$(basename "$entry")"
      target="$TARGET_DIR/.config/$name"

      if $BACKUP && ([ -e "$target" ] || [ -L "$target" ]); then
        mv "$target" "$backup_root/.config/"
        continue
      fi

      if $UNLINK_SYMLINKS && [ -L "$target" ]; then
        rm "$target"
      fi
    done < <(find "$cfg_dir" -mindepth 1 -maxdepth 1 -print0)
  done
}

if $UNLINK_SYMLINKS || $BACKUP; then
  prepare_targets
fi

if [ "${#STOW_ARGS[@]}" -gt 0 ]; then
  stow --dir "$ROOT" --target "$TARGET_DIR" --ignore='\\.zshrc$' "${STOW_ARGS[@]}" "${package_list[@]}"
else
  stow --dir "$ROOT" --target "$TARGET_DIR" --ignore='\\.zshrc$' "${package_list[@]}"
fi

ZSHRC="$TARGET_DIR/.zshrc"
STARSHIP_SNIPPET='[ -f "$HOME/.config/zsh/starship.zsh" ] && source "$HOME/.config/zsh/starship.zsh"'

if [ -L "$ZSHRC" ] && [ ! -e "$ZSHRC" ]; then
  BACKUP="$TARGET_DIR/.zshrc.broken"
  if [ -e "$BACKUP" ] || [ -L "$BACKUP" ]; then
    BACKUP="$TARGET_DIR/.zshrc.broken.$(date +%Y%m%d-%H%M%S)"
  fi
  mv "$ZSHRC" "$BACKUP"
fi

if ! grep -q "starship.zsh" "$ZSHRC" 2>/dev/null; then
  if [ -f "$ZSHRC" ]; then
    {
      echo ""
      echo "# Starship prompt"
      echo "$STARSHIP_SNIPPET"
    } >>"$ZSHRC"
  else
    {
      echo "# Generated by nvim-configs dotfiles/setup.sh"
      echo "# Starship prompt"
      echo "$STARSHIP_SNIPPET"
    } >"$ZSHRC"
  fi
fi
