#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STOW_DIR="$ROOT/dotfiles"
DEFAULT_PACKAGES=(nvim ghostty lazygit starship zsh)

usage() {
  cat <<'USAGE'
Usage: ./setup.sh [--no-packages] [--no-fonts] [--no-link]

Sets up Neovim/Neovide/Ghostty/Lazygit dotfiles and optional dependencies.

Options:
  --no-packages   Skip installing packages (neovim/neovide/ghostty/etc)
  --no-fonts      Skip installing fonts
  --no-link       Skip symlinking dotfiles (stow)
  -h, --help      Show this help
USAGE
}

has_cmd() { command -v "$1" >/dev/null 2>&1; }

is_macos() { [[ "$(uname -s)" == "Darwin" ]]; }

INSTALL_PACKAGES=1
INSTALL_FONTS=1
LINK_CONFIGS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-packages) INSTALL_PACKAGES=0 ;;
    --no-fonts) INSTALL_FONTS=0 ;;
    --no-link) LINK_CONFIGS=0 ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
  shift
done

install_packages_macos() {
  if ! has_cmd brew; then
    echo "Homebrew not found. Install it from https://brew.sh and re-run."
    return
  fi
  brew install neovim neovide lazygit starship fzf ripgrep fd stow

  if brew list --cask ghostty >/dev/null 2>&1; then
    return
  fi

  if [[ -d "/Applications/Ghostty.app" ]]; then
    echo "Ghostty.app already exists in /Applications; skipping Homebrew cask install."
    return
  fi

  brew install --cask ghostty
}

install_fonts_macos() {
  if ! has_cmd brew; then
    echo "Homebrew not found. Skipping fonts. Install it from https://brew.sh"
    return
  fi
  if brew info --cask font-iosevka-nerd-font >/dev/null 2>&1; then
    brew install --cask font-iosevka-nerd-font
  else
    echo "font-iosevka-nerd-font cask not found; skipping font install."
  fi
}

link_configs() {
  if ! has_cmd stow; then
    echo "stow not found. Install it or re-run with --no-link."
    return 1
  fi
  local packages
  if [[ -n "${PACKAGES:-}" ]]; then
    read -r -a packages <<<"${PACKAGES}"
  else
    packages=("${DEFAULT_PACKAGES[@]}")
  fi
  stow -d "$STOW_DIR" -t "$HOME" --ignore='\\.zshrc$' "${packages[@]}"
}

ensure_zshrc_sources_starship() {
  local zshrc="$HOME/.zshrc"
  local line='[ -f "$HOME/.config/zsh/starship.zsh" ] && source "$HOME/.config/zsh/starship.zsh"'

  if [[ -L "$zshrc" && ! -e "$zshrc" ]]; then
    local backup="$HOME/.zshrc.broken"
    if [[ -e "$backup" || -L "$backup" ]]; then
      backup="$HOME/.zshrc.broken.$(date +%Y%m%d-%H%M%S)"
    fi
    mv "$zshrc" "$backup"
  fi

  if [[ ! -f "$zshrc" ]]; then
    {
      echo "# Generated by nvim-configs setup.sh"
      echo "# Starship prompt"
      echo "$line"
    } >"$zshrc"
    return
  fi

  if ! grep -q "starship.zsh" "$zshrc"; then
    {
      echo ""
      echo "# Starship prompt"
      echo "$line"
    } >>"$zshrc"
  fi
}

main() {
  if [[ $INSTALL_PACKAGES -eq 1 ]]; then
    if is_macos; then
      install_packages_macos
    else
      echo "Package install is only implemented for macOS right now."
    fi
  fi

  if [[ $INSTALL_FONTS -eq 1 ]]; then
    if is_macos; then
      install_fonts_macos
    else
      echo "Font install is only implemented for macOS right now."
    fi
  fi

  if [[ $LINK_CONFIGS -eq 1 ]]; then
    link_configs
    ensure_zshrc_sources_starship
  fi

  echo "Setup complete."
}

main
